### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by PierceMcGeough** [gruntjs/grunt-contrib-cssmin#160]
Working on Windows I used npm install grunt-contrib-cssmin --save-dev but it came up with the following. I also tried it as root admin as it suggests. I have had a similar error with other contribs but then again others such as concat, imagemin, uglify and watch work ok.
```
Error: connect EACCES
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
  {  [Error: connect EACCES]
    code: 'EACCES',
    errno: 'EACCES',
    syscall: 'connect',
    parent: 'example-project' }

Please try running this command again as root/Administrator.

_system_ Windows_NT 6.1.7601
_command_ "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-contrib-cssmin" "--save-dev"
_cwd_ C:\Users\Pierce\Desktop\myproject
_node -v_ v0.10.32
_npm -v_ 1.4.28
_syscall_ connect
_code_ EACCES
_errno_ EACCES
_stack_ Error: connect EACCES
_stack_    at errnoException (net.js:904:11)
_stack_    at Object.afterConnect [as oncomplete] (net.js:895:19)

Additional logging details can be found in:
    C:\Users\Pierce\Desktop\myproject\npm-debug.log
_not ok_ code 0
```

**Comment by sindresorhus** [comment]
:arrow_forward: https://github.com/npm/npm/issues/new
